version: '3.4'

services:
  triceratops.api:
    image: ${DOCKER_REGISTRY-}triceratopsapi
    build:
      context: .
      dockerfile: Triceratops.Api/Dockerfile
    environment:
      DB_USE_MEMORY: "true"
  triceratops.mongo:
    hostname: "triceratops.mongo"
    image: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
