version: '3.7'

services:
  triceratops.api:
    hostname: triceratops.api
    container_name: Triceratops.Api
    image: ${DOCKER_REGISTRY-}triceratopsapi    
    restart: always
    build:
      context: .
      dockerfile: Triceratops.Api/Dockerfile
    networks:
      - triceratops.network

  triceratops.dashboard:
    hostname: triceratops.dashboard
    container_name: Triceratops.Dashboard
    image: ${DOCKER_REGISTRY-}triceratopsdashboard    
    restart: always
    build:
      context: .
      dockerfile: Triceratops.Dashboard/Dockerfile
    networks:
      - triceratops.network

  triceratops.mongo:
    image: mongo
    container_name: Triceratops.Mongo
    hostname: triceratops.mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - triceratops.network

networks:
  triceratops.network:
    name: triceratops.network
    driver: bridge
