version: '3.7'

services:
  triceratops.api:
    hostname: "triceratops.api"
    image: ${DOCKER_REGISTRY-}triceratopsapi
    ports:
      - "9090:80"
    restart: always
    build:
      context: .
      dockerfile: Triceratops.Api/Dockerfile
    environment:
      DB_USE_MEMORY: "true"
    networks:
      - triceratops.network
  triceratops.dashboard:
    hostname: "triceratops.dashboard"
    image: ${DOCKER_REGISTRY-}triceratopsdashboard
    ports:
      - "8080:80"
    restart: always
    build:
      context: .
      dockerfile: Triceratops.Dashboard/Dockerfile
    networks:
      - triceratops.network
  triceratops.mongo:
    image: "mongo"
    container_name: Triceratops.Mongo
    hostname: "triceratops.mongo"
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - triceratops.network

networks:
  triceratops.network:
    name: triceratops.network
    driver: bridge
