version: '3.4'

services:
  triceratops.api:
    image: ${DOCKER_REGISTRY-}triceratopsapi
    ports:
     - "8080:80"
    restart: always
    build:
      context: .
      dockerfile: Triceratops.Api/Dockerfile
    environment:
      DB_USE_MEMORY: "true"
  triceratops.mongo:
    image: "mongo"
    hostname: "triceratops.mongo"
    ports:
     - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
