version: '3.7'

services:
  triceratops.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
    build:
      args:
        BUILD_CONFIGURATION: Debug
    ports:
      - "81:80"

  triceratops.dashboard:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    build:
      args:
        BUILD_CONFIGURATION: Debug
    ports:
      - "82:80"

  triceratops.mongo:
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password